WITH S AS (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS TOTAL_COUNT FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%' GROUP BY BOOK_ID)

SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_COUNT * PRICE) AS TOTAL_SALES FROM BOOK
JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
JOIN S ON S.BOOK_ID = BOOK.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;