SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT ONLINE_SALE .USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT ONLINE_SALE .USER_ID)/(SELECT COUNT(*) AS JOIN_COUNT FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO FROM ONLINE_SALE 
JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH