WITH ECOLI_QUARTER AS (SELECT ID, 
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN 1
        WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN 2
        WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN 3
        ELSE 4
    END AS QUARTER
FROM ECOLI_DATA)

SELECT CONCAT(QUARTER, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT 
FROM ECOLI_QUARTER
GROUP BY QUARTER
ORDER BY QUARTER;