WITH J AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL FROM JULY GROUP BY FLAVOR)

SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF
JOIN J ON J.FLAVOR = FIRST_HALF.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER + SUM_TOTAL DESC LIMIT 3;