SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DOCTOR.DR_NAME, APNT_YMD FROM APPOINTMENT
JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
JOIN PATIENT ON PATIENT.PT_NO = APPOINTMENT.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APNT_YMD;
