SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS USER
JOIN USED_GOODS_BOARD AS BOARD ON USER.USER_ID = BOARD.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;