SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE FROM REST_REVIEW
JOIN MEMBER_PROFILE ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE REST_REVIEW.MEMBER_ID IN (SELECT * FROM (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1) AS A)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;


