SELECT ITEM_TREE.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY FROM ITEM_TREE
JOIN ITEM_INFO ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;