SELECT DATA1.ID, DATA1.GENOTYPE, DATA2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS DATA1
JOIN ECOLI_DATA AS DATA2 ON DATA1.PARENT_ID = DATA2.ID
WHERE DATA1.GENOTYPE & DATA2.GENOTYPE = DATA2.GENOTYPE
ORDER BY ID;