# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#     (MAX(SIZE_OF_COLONY) - SIZE_OF_COLONY) AS YEAR_DEV, 
#     ID FROM ECOLI_DATA

WITH YEAR_MAX_SIZE AS (SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS MS FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE))

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (YEAR_MAX_SIZE.MS - SIZE_OF_COLONY) AS YEAR_DEV, ID FROM ECOLI_DATA
JOIN YEAR_MAX_SIZE ON YEAR_MAX_SIZE.Y = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;
