SELECT SUM(SCORE) AS SCORE, HR_GRADE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE
JOIN HR_EMPLOYEES ON HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
GROUP BY EMP_NO HAVING SUM(SCORE) IN (SELECT MAX(SUM_SCORE) FROM (SELECT SUM(SCORE) AS SUM_SCORE FROM HR_GRADE GROUP BY EMP_NO) AS A)
